#Type Path                        Mode User Group Age    Argument
# Where disks will be mounted (mount points are created by the mount units)
d     /mnt/disks                  755  root root  -      -
# Mount point for the merged filesystem (mergerFS)
d     /mnt/pool                   755  root root  -      -


