cache.files=off
# most free space: fill disk evenly starting with big disks
category.create=mfs
func.getattr=newest
dropcacheonclose=false
# refuse to write to a branch that have less than 100G free
minfreespace=100G
# nice output in `df -h`
fsname=mergerfs.tank
