# A larger disk holds the parity data
parity /mnt/disks/16tb/snapraid.parity

# file that holds a list of all files and checksums
content /mnt/disks/16tb/snapraid.content
# Also hold a copy on the boot disk for redundancy
content /var/snapraid/snapraid.content
# and a third one in one of the data disk
content /mnt/disks/4tb-1/snapraid.content

data 4tb-1 /mnt/disks/4tb-1
data 4tb-2 /mnt/disks/4tb-2

# Only protect sensitive data.
# From the doc :
#   > If no pattern matches, the file is excluded if the last pattern specified is an include,
#   > or included if the last pattern specified is an exclude. 
# Paths here are relative to the array root, so where disks are mounted.
exclude /lost+found/
include /immich/
include /syncthings/
include /backups/
