# Network Manager nmconnections profiles must be readable only by root
# but that would be annoying for git. So let's apply the correct permissions at boot.
z       /etc/NetworkManager/system-connections        0700  root  root  -    -
z       /etc/NetworkManager/system-connections/*      0600  root  root  -    -
